# Generated by Django 4.2 on 2023-04-22 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('strand', models.CharField(blank=True, choices=[('STEM', 'Science, Technology, Engineering, And Mathematics'), ('ABM', 'Accountancy, Business, and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('TVL', 'Technical-Vocational Livelihood'), ('ADT', 'Arts and Design'), ('ICT', 'Information and Communications Technology')], max_length=100, null=True)),
                ('pronouns', models.CharField(blank=True, choices=[('F', 'She / Her'), ('M', 'He / Him'), ('T', 'They / Them'), ('AP', 'Any Pronouns'), ('X', 'Rather Not Say')], max_length=100, null=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='images')),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('onedlink', models.URLField(blank=True, null=True)),
                ('about', models.CharField(blank=True, max_length=2550, null=True)),
                ('user_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_output1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('img_output2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('img_output3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lang', models.CharField(blank=True, max_length=255, null=True)),
                ('lang_proficiency', models.CharField(blank=True, choices=[('BG', 'Beginner | limited working'), ('MR', 'Mid-range | Conversation'), ('AD', 'Advanced | Native speaker')], max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_interest', models.CharField(blank=True, choices=[('sports', 'Sports'), ('travel', 'Travelling'), ('photo', 'Photography / Films'), ('art', 'Art'), ('gaming', 'Gaming'), ('pets', 'Pets'), ('music', 'Music'), ('literature', 'Literature')], max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educ_type', models.CharField(blank=True, choices=[('PS', 'Preschool'), ('GS', 'Grade School'), ('HS', 'High School'), ('SHS', 'Senior High School'), ('COL', 'College')], max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_club', models.CharField(blank=True, choices=[('acads', 'Academics (Math, Science, Etc.)'), ('red_cross', 'Red Cross'), ('photo', 'Photography'), ('sports', 'Sports'), ('arts', 'Art'), ('school_news', 'School Newspaper'), ('performance', 'Performance')], max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
